version: '3.4'

services:
  redmine-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgresql.conf:/var/lib/postgresql/data/redmine/postgresql.conf
      - redmine-pglogs:/var/log/postgresql
      - redmine-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/redmine-data

  redmine:
    image: redmine:latest
    ports:
      - "3000:3000"
    volumes:
      - redmine-plugins:/usr/src/redmine/plugins
      - redmine-themes:/usr/src/redmine/public/themes
      - redmine-data:/usr/src/redmine/files
      - redmine-models:/usr/src/redmine/app/models/
      - /srv/storage/redmine/configuration.yml:/usr/src/redmine/config/configuration.yml
    environment:
      - REDMINE_DB_POSTGRES=redmine-db
      - REDMINE_DB_DATABASE=${POSTGRES_DB}
      - REDMINE_DB_USERNAME=${POSTGRES_USER}
      - REDMINE_DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDMINE_DB_PORT=5432

volumes:
  redmine-pglogs:
    driver: local
  redmine-pgdata:
    driver: local
  redmine-plugins:
    driver: local
  redmine-themes:
    driver: local
  redmine-data:
    driver: local
  redmine-models:
    driver: local
